remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: hacker
title: Data Science Career Journey Blog
author: Marc A. Aradillas
description: Codeup Somerville Cohort experience (Lessons, Challenges, Solutions, Thoughts)
