--- 
# remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-primer
title: Data Science Career Journey Blog
author: Marc A. Aradillas
description: Codeup Somerville Cohort experience (Lessons, Challenges, Solutions, Thoughts)
header_pages:
  - about.md
---
